name: cnn3d

params: 
  input_dim: 4 # 不重要
  in_channels: 7 # 特征维度
  lr: 1e-3
  epoch: 50
  batch: 8


nodes:
  - name: a
    type: conv3d
    in_channels: 7  #需要等于params: inchannels
    out_channels: 32
    kernel_size: 3
    padding: 1
    norm_type: batchnorm3d
    activation: relu
    input_from: input


  - name: b
    type: conv3d
    in_channels: 32
    out_channels: 32
    kernel_size: 3
    padding: 1
    norm_type: batchnorm3d
    activation: relu
    input_from: a

  - name: c
    type: conv3d
    in_channels: 32
    out_channels: 32
    kernel_size: 3
    padding: 1
    norm_type: batchnorm3d
    activation: relu
    input_from: a

  - name: merge
    type: add      # or concat
    input_from: [b, c]

  - name: d
    type: conv3d
    in_channels: 32
    out_channels: 64
    kernel_size: 3
    padding: 1
    norm_type: batchnorm3d
    activation: relu
    input_from: merge

  # - name: pool
  #   type: adaptiveavgpool3d
  #   output_size: 1
  #   input_from: d

  # - name: flatten
  #   type: flatten
  #   input_from: d

  - name: drop
    type: dropout
    p: 0.2
    input_from: d

  - name: e
    type: conv3d
    in_channels: 64
    out_channels: 2
    kernel_size: 3
    padding: 1
    norm_type: batchnorm3d
    # activation: sigmoid
    input_from: drop